spring:
  application:
    name: yotpoRecruitmentEventProducer
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
file:
  path: "data.json"
server:
  port: 8081
